#.travis.yml

language: node_js
node_js:
  - "10.15.3"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - cd ./functions && npm install

script: 
  - ng build --prod --configuration=production

after_success:
  - firebase deploy --only hosting --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change